### PR TITLE
more error handling and list_facts end point

### PR DESCRIPTION
**Pull request by Mcray3000**
Contains changes from my New Endpoints PR so look at that one first :)

### List Facts - `/{user_id}/lists/{list_id}/list_facts` (GET)

Provides a breakdown of nutritional information for each item in a shopping list, including total servings and macro and micronutrient values. Also provides a summary row with the total for all items.

**Request:**

- Path Parameters:
        - user_id: "integer": The ID of the user who owns the shopping list.
        - list_id: "integer": The ID of the shopping list.

**Response:**

```json
{
  "item_name_1": {
    "total_servings": "integer",
    "total_saturated_fat": "integer",
    "total_trans_fat": "integer",
    "total_dietary_fiber": "integer",
    "total_carbohydrates": "integer",
    "total_sugars": "integer",
    "total_protein": "integer"
  },
  "item_name_2": {
    // ... more items
  },
  "Total": {
    "total_servings": "integer",
    "total_saturated_fat": "integer",
    "total_trans_fat": "integer",
    "total_dietary_fiber": "integer",
    "total_carbohydrates": "integer",
    "total_sugars": "float",
    "total_protein": "float"
  }
}
```

**Possible Error Responses:**

*404 Not Found:*

Returned when the user, list, or association between them is not found.

```JSON
{
  "detail": "User does not exist."
}
```
```JSON
{
  "detail": "List does not exist."
}
```
```JSON
{
  "detail": "User is not associated with this list."
}
```
*204 No Content:*

Returned when the list is empty.

```JSON
{
  "detail": "List is empty, add something to it!"
}
```
*500 Internal Server Error:*

Returned when an unexpected error occurs during the processing of the request.

```JSON
{
  "detail": "Something went wrong {error_details}" 
}
```

## Other changes

- Removed unused preferences endpoints
- added regex and long/lat requirements so they all have to be real possible coords

### CODE REVIEW

**Review by kevinrutledge — APPROVED** [review]

**Comment by TLMatthies** [comment]
A bit repetitive on the name, maybe truncate it to /facts, instead of /list_facts.

**Comment by TLMatthies** [comment]
Another thing I noticed is that only one issue in 404 gets returned. Very minor issue, but if there's extra time (don't think there will be) maybe we could add in all the issues wrong with the request.

**Comment by TLMatthies** [comment]
list_facts returns with a 201 code, which means successfully created. Should be a 200

**Comment by TLMatthies** [comment]
Might want to add in error handling if there's no items in a list. Got this:

REQUEST:
curl -X 'GET' \
  'http://127.0.0.1:8000/users/6/lists/4/list_facts' \
  -H 'accept: application/json' \
  -H 'access_token: fartsmella21'

RESPONSE:
{
  "Total": {
    "total_servings": null,
    "total_saturated_fat": null,
    "total_trans_fat": null,
    "total_dietary_fiber": null,
    "total_carbohydrates": null,
    "total_sugars": null,
    "total_protein": null
  }
}

**Review by TLMatthies — APPROVED** [review]
Everything looks good to be merged after http code is changed from 201 to 200, and maybe error handling on lists that don't have items in them.

**Comment by Aiden-Rodriguez** [comment]
for list facts endpoint, should add a little description to the API; like how create user has "Creates a new user in the system. Returns the user_id of the created user."

**Comment by Aiden-Rodriguez** [comment]
For "/{user_id}/fulfill_list/{list_id}"
The way that the order by is done seems a little janky, by inputting 1, 2, or 3. 
I honestly don't know how you would fix this, and honestly its not a big deal, tried researching a little and came up with nothing.

Overall really good code

**Review by Aiden-Rodriguez — COMMENTED** [review]
look above comments, good work

**Review by Aiden-Rodriguez — APPROVED** [review]

**Pull request merged**
